<a href="https://colab.research.google.com/github/Smpests/KeepLearning/blob/master/jupyter-notebook/numpy%E9%83%A8%E5%88%86%E8%AE%A1%E7%AE%97.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# ufunc代表通用函数，操作对象是ndarray
# 实现了矢量化（向量化操作）
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
# 这里也可用zip()实现
z = np.add(x, y)
print(z)

[ 5  7  9 11]


In [14]:
# 自定义ufunc
import numpy as np

def myadd(x, y):
  return x + y

# 使用frompyfunc注册到numpy ufunc库中
# 3个参数：function已定义的函数名称，inputs函数允许输入的ndarray数量，outputs输出的数组的数量
myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))
# 查看函数类型
print(type(myadd))
print(type(np.concatenate))

# 减法
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
# 参数1是被减数
newarr = np.subtract(arr2, arr1)

print("减法: ", newarr)

# 乘法
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])
newarr = np.multiply(arr1, arr2)
print("乘法：", newarr)

# 除法
print("除法：", np.divide(arr2, arr1))

# 幂次方
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 33])
newarr = np.power(arr1, arr2)

print("幂次方", newarr)

# 求余数(取模)，两种方法结果一致
print("mod求余：", np.mod(arr1, arr2))
print("remainder求余：", np.remainder(arr1, arr2))

# divmod，将返回两个ndarray，0是商、1是余
print("求商和模：", np.divmod(arr1, arr2))

# 绝对值
arr = np.array([-1, -2, 1, 2, 3, -4])
print("绝对值：", np.absolute(arr))

[6 8 10 12]
<class 'numpy.ufunc'>
<class 'function'>
减法:  [ 10   1  -8 -17 -26 -35]
乘法： [ 200  420  660  920 1200 1500]
除法： [2.         1.05       0.73333333 0.575      0.48       0.41666667]
幂次方 [         1000       3200000     729000000 6553600000000          2500
             0]
mod求余： [ 1  0  0  0  0 27]
remainder求余： [ 1  0  0  0  0 27]
求商和模： (array([ 3,  4,  5,  5, 25,  1]), array([ 1,  0,  0,  0,  0, 27]))
绝对值： [1 2 1 2 3 4]


In [21]:
# 四舍五入近似值
import numpy as np

arr = np.trunc([-3.1666, 3.6667])
print("直接截断小数点后面的数：", np.trunc([-3.1666, 3.6667]))
print("fix同trunc也是截断：", np.fix([-3.1666, 3.6667]))

print("四舍五入保留2位小数：", np.around(np.random.rand(), 2))

print("四舍五入到最近的小整数：", np.floor([3.14, 3.68]))
# 和floor()相反
print("四舍五入到最近的大整数：", np.ceil([3.14, 3.68]))

直接截断小数点后面的数： [-3.  3.]
fix同trunc也是截断： [-3.  3.]
四舍五入保留2位小数： 0.31
四舍五入到最近的小整数： [3. 3.]
四舍五入到最近的大整数： [4. 4.]


In [26]:
# 对数
# 无法计算对数的元素结果会置为-inf或inf

import numpy as np

# numpy.arange(start=0, stop, step=1, dtype = None)生成[star, end)内的数据
arr = np.arange(1, 10)

print("2为底：", np.log2(arr))
print("10为底：", np.log10(arr))
print("e为底：", np.log(arr))

# 自定义以任何数为底的求对数
from math import log
nplog = np.frompyfunc(log, 2, 1)
print("12为底", nplog(144, 12))

2为底： [0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
10为底： [0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
e为底： [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
2.0


In [39]:
import numpy as np

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1, 2, 3]])

# 区别于add，sum默认会把两个array中的所有数相加得到一个累加值而不是一个array
newarr = np.sum([arr1, arr2])
print(newarr)

# axis表示下标发生变化的维度（维度从0开始），需要在该维度上操作数据
print(np.sum([arr1, arr2], axis=2))

# 累积和/前缀和
arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)
print("前缀和/累积和：", newarr)

# 连续乘：1*2*3*4
print(np.prod(np.array([1, 2, 3, 4])))
print(np.prod(np.array([[1, 2, 3], [4, 5, 6]])))
print(np.prod(np.array([[1, 2, 3], [4, 5, 6]]), axis=1))

# 前缀积
print("前缀积：", np.cumprod(np.array([5, 6, 7])))

# 连续减：例如，对于 [1, 2, 3, 4]，离散差将是 [2-1, 3-2, 4-3] = [1, 1, 1]
# 结果集长度将少1位
print("连续减：", np.diff(np.array([10, 15, 25, 5])))
# 将第n-1次的结果用于第n次的计算
print("连续减2次", np.diff(np.array([10, 15, 25, 5]), n=2))

12
[[6]
 [6]]
前缀和/累积和： [1 3 6]
24
720
[  6 120]
前缀积： [  5  30 210]
连续减： [  5  10 -20]
 [  5 -30]


In [45]:
# LCM（最小公倍数）

import numpy as np

num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print("最小公倍数：", x)
# 使用reduce在数组上找最小公倍数，并输出原数组维度-1的数组
arr = np.array([3, 6, 9])

print("array上的最小公倍数：", np.lcm.reduce(arr))
print("array上的最小公倍数：", np.lcm.reduce(np.arange(1, 11)))

# GCD（最大公分母）/HCF(最大公因数)

print("最大公因数：", np.gcd(6, 9))
print("array上的最大公因数：", np.gcd.reduce(np.arange(5, 11)))

最小公倍数： 12
array上的最小公倍数： 18
array上的最小公倍数： 2520
最大公因数： 3
array上的最大公因数： 1


In [52]:
# 三角函数（搁置）https://www.w3schools.com/python/numpy/numpy_ufunc_trigonometric.asp
# 双曲线（搁置）https://www.w3schools.com/python/numpy/numpy_ufunc_hyperbolic.asp

In [53]:
# 集合
import numpy as np

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
print("去重：", np.unique(arr))

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])
print("联合（并集）去重：", np.union1d(arr1, arr2))
# assume_unique有加速功能
print("交集：", np.intersect1d(arr1, arr2, assume_unique=True))
# 第一个参数中有第二个参数中没有的
print("差集", np.setdiff1d(arr1, arr2, assume_unique=True))
# 输出1中2没有的，2中1没有的
print("两个集合中的对称差异值：", np.setxor1d(arr1, arr2, assume_unique=True))

去重： [1 2 3 4 5 6 7]
联合（并集）去重： [1 2 3 4 5 6]
交集： [3 4]
差集 [1 2]
两个集合中都没有的值： [1 2 5 6]
